name: Main Commit Checks
on: [push]

env:
    CYPRESS_CACHE_FOLDER: ~/Library/Caches/Cypress

jobs:
    build:
        runs-on: macos-latest

        strategy:
            matrix:
                node: [18.20.3]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}

            - name: Cache pnpm store
              uses: actions/cache@v4
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('app/pnpm-lock.yaml') }}

            - name: Cache node_modules
              uses: actions/cache@v4
              with:
                  path: app/node_modules
                  key: ${{ runner.os }}-modules-${{ hashFiles('app/pnpm-lock.yaml') }}

            - run: sudo npm install -g pnpm

            - name: Install dependencies
              run: pnpm install --fetch-timeout 1000000
              working-directory: ./app

            - name: Fix npm cache permissions
              run: |
                  if [ -d "/Users/runner/.npm" ]; then
                    sudo chown -R $USER:$(id -gn $USER) /Users/runner/.npm
                  fi

            - name: Build app
              run: pnpm build --mode e2e
              working-directory: ./app
              env:
                  USE_HTTP: true
                  NODE_OPTIONS: --openssl-legacy-provider

            - name: Start static server
              run: |
                  cd app
                  npx serve -s dist -l 5000 &
                  echo "Static server PID: $!"
              env:
                  USE_HTTP: true

            - name: Wait for server
              run: npx wait-on 'http://localhost:5000/' --timeout 60000

            - name: Install Cypress binary
              run: |
                  cd app
                  npx cypress install --force

            - name: Run Cypress tests
              uses: cypress-io/github-action@v6
              env:
                  USE_HTTP: true
              with:
                  working-directory: ./app
                  config-file: cypress.config.js
                  wait-on: http://localhost:5000
                  browser: chrome
                  install: false

            - name: Extract screenshots to git
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: cypress-screenshots
                  path: app/cypress/screenshots

            - name: Extract videos to git
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: cypress-videos
                  path: app/cypress/videos
